update data

diff --git a/.github/workflows/upload-release.yml b/.github/workflows/upload-release.yml
--- a/.github/workflows/upload-release.yml
+++ b/.github/workflows/upload-release.yml
@@ -60,4 +60,16 @@ jobs:
       - name: Create release
         shell: bash
         run: |
-          curl -d '{"prerelease": ${{ github.event.release.prerelease }}, "commit_hash": "$GITHUB_SHA", "tag": ${{ github.event.release.tag_name }}, "gd": ${{ steps.release-data.output.PLATFORM_INFO }}}' -H "Content-Type: application/json" -H "Authorization: Bearer ${{ secrets.INDEX_TOKEN }}" https://api.geode-sdk.org/v1/loader/versions
+          CODE=`curl -d '{"prerelease": ${{ github.event.release.prerelease }}, "commit_hash": "$GITHUB_SHA", "tag": ${{ github.event.release.tag_name }}, "gd": ${{ steps.release-data.output.PLATFORM_INFO }}}' \
+            --write-out "%{http_code}"
+            --silent
+            --output /dev/null
+            -H "Content-Type: application/json" \
+            -H "Authorization: Bearer ${{ secrets.GEODE_INDEX_TOKEN }}" \
+            https://api.geode-sdk.org/v1/loader/versions`
+
+          if [ $CODE != "204" ]
+          then
+            echo "Request failed with response $CODE"
+            exit 1
+          fi
